name: Cypress Tests

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: npm start &
        env:
          NODE_ENV: test

      - name: Wait for the app to start (optional)
        run: sleep 10

      - name: Check if the server is running
        run: curl -I http://localhost:3000/health

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: "**/*.cy.js"

      - name: Capture Node.js app logs
        if: failure()
        run: |
          echo "Node.js App Logs:"
          cat ./logs/app.log || echo "No logs found"

      - name: Stop application
        run: kill $(lsof -t -i:3000)
